version: '3.8'

name: deile_server_forge

services:
  dynmap_mysql:
    image: mysql:8.0.32
    container_name: dynmap-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: dynmap
      MYSQL_USER: dynmap
      MYSQL_PASSWORD: dynmap
      TZ: Asia/Tokyo
      # ports:
      # - 3306:3306
      # - 33060:33060
    volumes:
      - type: bind
        source: /home/keita/data/mysql/
        target: /etc/mysql/conf.d/
      - type: volume
        source: mysql
        target: /var/lib/mysql
    networks:
      - forge_network

  forge:
    image: itzg/minecraft-server
    container_name: forge
    environment:
      TYPE: FORGE
      VERSION: 1.19.3
      MEMORY: 8G
      TZ: Asia/Tokyo
      EULA: TRUE
      RCON_PASSWORD: minecraft
    ports:
      - 21143:21143
      - 25565:25565
      # - 25575:25575
      # - 8123:8123
    volumes:
      - type: bind
        source: /home/keita/data/minecraft/forge/
        target: /data/
    networks:
      - forge_network

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    environment:
      TZ: Asia/Tokyo
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP.UTF-8
      LC_ALL: ja_JP.UTF-8
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /home/keita/data/cron/etc/letsencrypt/
        target: /etc/letsencrypt/
      - type: bind
        source: /home/keita/data/nginx/conf.d/
        target: /etc/nginx/conf.d/
      - type: bind
        source: /home/keita/data/nginx/html/
        target: /usr/share/nginx/html/
      - type: bind
        source: /home/keita/data/nginx/log/
        target: /var/log/nginx/"
    networks:
      - forge_network

volumes:
  mysql:
    name: mysql

networks:
  forge_network:
    name: forge_network
    driver: bridge
    ipam: 
      driver: default
      config:
        - subnet: 192.168.100.0/24
